version: "3.9"
services:


  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - .env

  redis:
    image: redis:latest # Redis image
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379" # Expose Redis on default port
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD} # Optionally set a password for Redis (if you want)
    volumes:
      - redis_data:/data # Persist Redis data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis # New environment variable for Redis
      - REDIS_PORT=6379 # Redis default port
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
      - redis # Make sure the app waits for Redis to start
    env_file:
      - .env

volumes:
  mysql_data:
  redis_data: # Volume for Redis data persistence
